twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
    paths:
        '%kernel.project_dir%/public/img': image
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']