<?php

namespace ContainerRCRICNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0sLxTfZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0sLxTfZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0sLxTfZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'guideRepository' => ['privates', 'App\\Repository\\GuideRepository', 'getGuideRepositoryService', true],
            'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService', true],
            'itinerariesRepository' => ['privates', 'App\\Repository\\ItinerariesRepository', 'getItinerariesRepositoryService', true],
        ], [
            'guideRepository' => 'App\\Repository\\GuideRepository',
            'imageRepository' => 'App\\Repository\\ImageRepository',
            'itinerariesRepository' => 'App\\Repository\\ItinerariesRepository',
        ]);
    }
}
