<?php

namespace ContainerRCRICNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZXfLtAMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zXfLtAM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zXfLtAM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'guide' => ['privates', '.errored..service_locator.zXfLtAM.App\\Entity\\Guide', NULL, 'Cannot autowire service ".service_locator.zXfLtAM": it needs an instance of "App\\Entity\\Guide" but this type has been excluded in "config/services.yaml".'],
            'languageRepository' => ['privates', 'App\\Repository\\LanguageRepository', 'getLanguageRepositoryService', true],
        ], [
            'entityManager' => '?',
            'guide' => 'App\\Entity\\Guide',
            'languageRepository' => 'App\\Repository\\LanguageRepository',
        ]);
    }
}
