<?php

namespace ContainerRCRICNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_WiANzy7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.WiANzy7' shared service.
     *
     * @return \App\Controller\ApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\LocationController::new()": the $apiController argument is type-hinted with the non-existent class or interface: "App\\Controller\\ApiController". Did you forget to add a use statement?');
    }
}
