<?php

namespace ContainerRCRICNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fp6TaauService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fp6Taau' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fp6Taau'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'itinerariesRepository' => ['privates', 'App\\Repository\\ItinerariesRepository', 'getItinerariesRepositoryService', true],
        ], [
            'itinerariesRepository' => 'App\\Repository\\ItinerariesRepository',
        ]);
    }
}
