<?php

namespace ContainerRCRICNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuideService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VmpGnME.App\Entity\Guide' shared service.
     *
     * @return \App\Entity\Guide
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VmpGnME": it needs an instance of "App\\Entity\\Guide" but this type has been excluded in "config/services.yaml".');
    }
}
