<?php

namespace ContainerRCRICNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O0VupqY.App\Entity\Language' shared service.
     *
     * @return \App\Entity\Language
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O0VupqY": it needs an instance of "App\\Entity\\Language" but this type has been excluded in "config/services.yaml".');
    }
}
