<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Guide extends \App\Entity\Guide implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'articles' => [parent::class, 'articles', null],
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_location' => [parent::class, 'id_location', null],
        "\0".parent::class."\0".'itineraries' => [parent::class, 'itineraries', null],
        "\0".parent::class."\0".'languages' => [parent::class, 'languages', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'telNumber' => [parent::class, 'telNumber', null],
        "\0".parent::class."\0".'user_id' => [parent::class, 'user_id', null],
        'articles' => [parent::class, 'articles', null],
        'bio' => [parent::class, 'bio', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'id_location' => [parent::class, 'id_location', null],
        'itineraries' => [parent::class, 'itineraries', null],
        'languages' => [parent::class, 'languages', null],
        'lastname' => [parent::class, 'lastname', null],
        'telNumber' => [parent::class, 'telNumber', null],
        'user_id' => [parent::class, 'user_id', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
