controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_languages_get:
    path: /api/languages
    methods: GET
    controller: App\Controller\LanguageController::getLanguages

api_languages_post:
    path: /api/languages
    methods: POST
    controller: App\Controller\LanguageController::addLanguage
