<?php

namespace ContainerY4rwkug;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AFK0T3kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aFK0T3k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aFK0T3k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'guideRepository' => ['privates', 'App\\Repository\\GuideRepository', 'getGuideRepositoryService', true],
        ], [
            'entityManager' => '?',
            'guideRepository' => 'App\\Repository\\GuideRepository',
        ]);
    }
}
