<?php

namespace ContainerY4rwkug;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WqugX0nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wqugX0n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wqugX0n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'apiController' => ['privates', '.errored.WiANzy7', NULL, 'Cannot determine controller argument for "App\\Controller\\LocationController::new()": the $apiController argument is type-hinted with the non-existent class or interface: "App\\Controller\\ApiController". Did you forget to add a use statement?'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'apiController' => '?',
            'entityManager' => '?',
        ]);
    }
}
