<?php

namespace ContainerY4rwkug;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItineraries2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gTtmPI1.App\Entity\Itineraries' shared service.
     *
     * @return \App\Entity\Itineraries
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gTtmPI1": it needs an instance of "App\\Entity\\Itineraries" but this type has been excluded in "config/services.yaml".');
    }
}
