<?php

namespace ContainerY4rwkug;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItinerariesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ItinerariesType' shared autowired service.
     *
     * @return \App\Form\ItinerariesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ItinerariesType.php';

        return $container->privates['App\\Form\\ItinerariesType'] = new \App\Form\ItinerariesType();
    }
}
