<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRCRICNp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRCRICNp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRCRICNp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRCRICNp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRCRICNp\App_KernelDevDebugContainer([
    'container.build_hash' => 'RCRICNp',
    'container.build_id' => '430ab4ab',
    'container.build_time' => 1697119262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRCRICNp');
